### ISSUE TITLE
[QUESTION] How to override i18n assignments for Mega Menu

### ISSUE THREAD

**Issue by at88mph** [wet-boew/gcweb-jekyll#32]
We're in the process of upgrading to WET-4 using this Jekyll plugin.  There is a configuration switch to remove the Mega Menu (`page.nomenu`), and there is an i18n variable (`i18nText-menuAjax`) to replace the contents of the Mega Menu, but it seems to be inaccessible (amongst other variables in the `i18n.liquid` and `i18n-core.liquid`).  Is that true?  Can any of the i18n variables be overridden?

**Comment by delisma** [comment]
Yes, everything can be overridden. If you add your own _include folder with your custom `i18n.liquid` file. The `i18n.liquid` and `i18n-core.liquid` have to follow the same data structure because Jekyll doesn't support partial overrides.

**Comment by at88mph** [comment]
That did indeed work.  Thank you for the quick reply.
