### ISSUE TITLE
[FEATURE] Allow the background images on the Splash page to be configurable.

### ISSUE THREAD

**Issue by at88mph** [wet-boew/gcweb-jekyll#33]
In order to facilitate different presentations for different organizations, the blurred backgrounds of the splash page (language selector) could be configured.  Some organizations within NRC, for example, have medical images that would be more appropriate and representative, or like the Canadian Astronomy Data Centre, which would display astronomical images.

Modifying the existing `layout-splashpage.html` would alleviate having to replace that entire file in the local project, and thus, missing out on updates.

See here for an example:
http://206-12-98-60.cloud.computecanada.ca

**Comment by duboisp** [comment]
Thank for your contribution.

As I mentioned in the PR  #34 that change would need to be completed in GCWeb repository: https://github.com/wet-boew/GCWeb/
